// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH69csG27Hgic9daTrNuPiU8624m3tpOY',
    appId: '1:484179079649:web:a7d00e575d9a54bf7b22a0',
    messagingSenderId: '484179079649',
    projectId: 'new-evently',
    authDomain: 'new-evently.firebaseapp.com',
    storageBucket: 'new-evently.firebasestorage.app',
    measurementId: 'G-JHNGL315WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAUJvfL4hF3lZ9YmvJjSpcFxMfLSUtur4',
    appId: '1:484179079649:android:ed2f5c08eee260687b22a0',
    messagingSenderId: '484179079649',
    projectId: 'new-evently',
    storageBucket: 'new-evently.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOsmm36ea7zvKOKZrEuUU83F27e-_phI',
    appId: '1:484179079649:ios:a6113c5d1f4584627b22a0',
    messagingSenderId: '484179079649',
    projectId: 'new-evently',
    storageBucket: 'new-evently.firebasestorage.app',
    iosBundleId: 'com.example.newEvently',
  );
}
